
# ========================
# Consts Public
# ========================

DEFAULT_PRICELIST_CURRENCY = 'EUR'
DEFAULT_LICENSE_TYPE       = "Project License"

TABLE_IDX_MAJOR_VERSION_NAME       = 0
TABLE_IDX_PRODUCT_NAME             = 1
TABLE_IDX_PRODUCT_ITEM_NAME        = 2
TABLE_IDX_PRODUCT_ITEM_DESCRIPTION = 3
TABLE_IDX_PRICELIST                = 4
TABLE_IDX_ARTICLE_NUMBER           = 5
TABLE_IDX_LICENSE_TYPE_NAME        = 6
TABLE_IDX_AAV_CURRENCY             = 7
TABLE_IDX_QUANTITY                 = 8
TABLE_IDX_UNIT_PRICE               = 9
TABLE_IDX_VALID_DATE               = 10
TABLE_IDX_SALES_REGION             = 11
TABLE_IDX_PRODUCT_GROUP_ID         = 12
TABLE_IDX_SF_PRICE_BOOK            = 13
TABLE_IDX_SF_PRODUCT_ID            = 14
TABLE_IDX_SF_PRICE_BOOK_ENTRY      = 15
TABLE_IDX_LICENSE_TYPE_ID          = 16
TABLE_SIZE = TABLE_IDX_LICENSE_TYPE_ID + 1



TABLE_LICENSE_TYPE_IDX_CODE                   = 0
TABLE_LICENSE_TYPE_IDX_NAME                   = 1
TABLE_LICENSE_TYPE_IDX_DESCRIPTION            = 2
TABLE_LICENSE_TYPE_IDX_LICENSE_DURATION       = 3
TABLE_LICENSE_TYPE_IDX_MAINTENANCE_DURATION   = 4
TABLE_LICENSE_TYPE_IDX_EXPECTED_DELIVERY_TIME = 5
TABLE_LICENSE_TYPE_IDX_PAYMENT_MODEL          = 6
TABLE_LICENSE_TYPE_IDX_EXPECTED_INVOICE_DATE  = 7
TABLE_LICENSE_TYPE_IDX_GRANT_OF_RIGHTS        = 8
TABLE_LICENSE_TYPE_IDX_PROFILE                = 9
TABLE_LICENSE_TYPE_IDX_LICENSE_METHOD         = 10
TABLE_LICENSE_TYPE_IDX_PERPETUAL              = 11
TABLE_LICENSE_TYPE_IDX_UPDATE_RIGHT           = 12
TABLE_LICENSE_TYPE_SIZE = TABLE_LICENSE_TYPE_IDX_UPDATE_RIGHT + 1

